services:
  - type: web
    name: recipe-api
    env: python
    buildCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn your_project_name.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"