# Generated by Django 5.2 on 2025-05-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
