# Generated by Django 5.2 on 2025-05-09 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_calories', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_protein', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_carbs', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_fat', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_cuisines', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
