# Generated by Django 5.2 on 2025-05-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
