# Generated by Django 5.2 on 2025-05-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='preferred_cuisines',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preferred_nutrients',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preferred_tags',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.DeleteModel(
            name='CuisinePreference',
        ),
        migrations.DeleteModel(
            name='NutrientPreference',
        ),
        migrations.DeleteModel(
            name='TagPreference',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
