# Generated by Django 5.2 on 2025-05-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cuisine_dietaryrestriction_nutrient_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='major_ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='api.majoringredient'),
        ),
    ]
