# Generated by Django 5.2.1 on 2025-05-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_majoringredient_recipe_major_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='api.cuisine'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dietary_restrictions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='api.course'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='api.dietaryrestriction'),
        ),
    ]
