# Generated by Django 5.2.1 on 2025-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryrestriction',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
