# Generated by Django 5.2.1 on 2025-05-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_nutrients',
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
    ]
